name: MDI Mechanic report

on: workflow_dispatch

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install MDI Mechanic
        run: pip install mdimechanic

      - name: Build the MDI Engine
        run: mdimechanic build

      - name: Create MDI Mechanic report
        run: mdimechanic report

      - name: Run custom MDI Mechanic tests
        run: |
          mdimechanic run --name "engine"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update MDI Mechanic report
